language: node_js
node_js:
  - "14"

before_install:
  - npm run dev
  - npm run build
  - npm run export
  - touch out/.nojekyll

branches:
  only:
    - main

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main

notifications:
  email:
    recipients:
      - nant0313@gmail.com
